import "./globals.css";
import type { Metadata } from "next";
import { Tilt_Neon } from "next/font/google";
import { Providers } from "../provider";
import { AppBarClient } from "../components/appbarClient";
import clsx from "clsx";
const neon = Tilt_Neon({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <Providers>
        <body className={clsx(neon.className)}>
          <AppBarClient />
          {children}
        </body>
      </Providers>
    </html>
  );
}
